### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by SadaleNet** [lionello/nodemcu-httpd#3]
Hello @lionello , any chance to add an FOSS license to this repo?

Context: I'm volunteering to help DSL on working on a backward-compatible hardware revision of your LED lighting board design with an extra color channel (https://github.com/dimsumlabs/dsl-lights-v2-ilosuno). I'd like to modify your software repo for supporting the extra channel. However, I'm not willing to contribute to a software repo without a proper license.

**Comment by lionello** [comment]
Done !
